project 'LYConvenienceKitDome.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYConvenienceKitDome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for LYConvenienceKitDome
# 加载提示
  pod 'SnapKit'
# 网络请求
  pod 'Kingfisher'


end
